#! /bin/bash
osascript -e 'tell application "Music" to if player state is playing then name of current track & " - " & artist of current track'
# osascript -e 'tell application "Spotify" to if player state is playing then name of current track & " - " & artist of current track'
