#!/usr/bin/env node

import { Dex } from '@pkmn/dex';
import { Generations } from '@pkmn/data';

const gens = new Generations(Dex);
const gen2 = gens.get(2);

function randomItem(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

const allPokemon = Array.from(gen2.species);
const pokemon = randomItem(allPokemon);

const learnsets = gen2.learnsets;
const learnset = await learnsets.get(pokemon.name);
let allPokemonSkills = [];

if (learnset) {
    allPokemonSkills = Object.keys(learnset.learnset || {}).flat();
}

const skillId = randomItem(allPokemonSkills);
const skill = gen2.moves.get(skillId);

if (!skill) {
    throw new Error(`Could not find skill ${skillId} for ${pokemon.name}`);
}

const sentence = `tslatchers ${pokemon.name} used ${skill.name}`;
console.log(sentence.replace(/\s/g, "-").toLowerCase().replace(/[^\x00-\x7F]/g, ""));
